name: Continuous Integration

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 'nightly'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install

      - name: Install Foundry libraries
        run: forge install

      - name: Compile with Hardhat
        run: pnpm hardhat compile

      - name: Compile with Foundry
        run: forge build

      - name: Run Hardhat Tests
        run: pnpm hardhat test

      - name: Run Foundry Tests
        run: forge test
